### PR TITLE
Custom Rules for TypeScript and ES6

### LINKED ISSUE #25: no-multiline-var-declarations does not allow for individual settings
## Problem

The `no-multiline-var-declarations` rule does not allow for individual settings for each of the types of declarations (`var`, `let`, `const`). This causes a problem for `const` declarations, since you can't declare the constant without initializing it. So it's impossible to do the following:

```javascript
const myObj = {
   a: 1,
   func: function() {
      doSomething();
   },
};
```

## Proposed Solution

Add optional, individual settings for each of the declaration types. 

Also, add a setting to allow multiline declarations only on `single` declarations. This would allow:
```javascript
const NUM_1 = 1,
      NUM_2 = 2;

const myObj = {
   a: 1,
   func: function() {
      doSomething();
   },
};
```
But would disallow:
 ```javascript
const NUM_1 = 1,
       NUM_2 = 2,
       myObj = {
          a: 1,
          func: function() {
             doSomething();
          },
       };
```

### LINKED ISSUE #26: Add rule to disallow arrow functions on TypeScript class properties
## Problem

Arrow functions do not work well with inheritance. When inheriting a class with an arrow function property, you cannot use `super` to call the original method. It is better to force the use of class members instead.

**Reference:** [TypeScript Book](https://github.com/basarat/typescript-book/blob/master/docs/arrow-functions.md#tip-arrow-functions-and-inheritance)

## Solution

Since there is no currently available rule for this, it would be good to add a rule in this plugin.

## Invalid Code Sample

```javascript
class MyClass {
   public arrow = () => {
      doSomething();
   }
}
```

### Valid Code Sample

```javascript
class MyClass {
   public notAnArrow() {
      doSomething();
   }
}
```

### LINKED ISSUE #27: Force all TypeScript files to be modules
## Problem

If a TypeScript file is not parsed as a module, it will put all variable declarations on the global scope. To determine if a file is a module, TypeScript looks for the existence of either Import and Export statements, or both. If no import/export statements exist, it parses the file as a script and puts all declarations on the global scope. 

## Solution

Add a rule to force all files to have at least one import or export statement. If a file is meant to be a script, we can "comment disable" this rule on that file.

## Invalid Code Sample

This file does not export anything:
```javascript
const initializer = require('initializer'); // require statements do not constitute "imports"

initializer();
```

## Valid Code Samples

``` javascript

import initializer from 'initializer';

initializer();
```

```javascript
export const MY_CONST = 1;
```

### LINKED ISSUE #28: Enforce block scope for case statements
## Problem

We would like to force case statements to be treated as blocks, like `if/while/for` etc. There is currently no rule to force this.

## Solution

Add a rule that forces the use of curly braces around case statements.

## Invalid Code Example

```javascript
switch (x) {
   case 2: 
      doSomethingWith2(x);
      break;
   default:
      doSomethingWithEverythingElse(x);
}
```

## Valid Code Example

```javascript
switch (x) {
   case 2: {
      doSomethingWith2(x);
      break;
   }
   default: {
      doSomethingWithEverythingElse(x);
   }
}
```

### PR DESCRIPTION
**Pull request by jimjenkins5**
Add and modify rules for TypeScript/ES6 specific code. 

The following rules were added or modified:
 * `no-multiline-var-declarations` - Fixes #25 
     * Added the ability to override each individual declaration type (`let`, `var`, `const`)
     * Added the ability to allow multiline declarations when the variable being declared is the only one in the declaration block.
 * `no-arrow-for-class-properties` - Fixes #26 
    * Rule to disallow class properties that are arrow functions
 * `module-files-only` - Fixes #27 
    * Rule to force all files to have either an `import` or `export` statement, ensuring that they are modules.
 * `block-scope-case` - Fixes #28 
    * Rule to force declaring block scope for all case statements.

There is also a commit to prepare for TypeScript rules. This commit removes changes the node dependency to > v6 and adds a rule tester configuration that can be used for TypeScript rule tests.

### CODE REVIEW

File: lib/rules/no-multiline-var-declaration.js [hunk 1]
```diff
@@ -4,9 +4,41 @@
...
+               },
+            },
+         },
+      ],
+   },
+
    create: function(context) {
+      var options;
+
+      options = _.assign(DEFAULT_OPTIONS, context.options[0] || {});
```
Comment (yokuze) [inline lib/rules/no-multiline-var-declaration.js]: The signature of `assign` is `assign(destination, sources*)`. So, I think the properties in `context.options[0]` would get copied over to `DEFAULT_OPTIONS`, which would permanently modify `DEFAULT_OPTIONS` for subsequent uses.

Normally, we: `_.extend({}, DEFAULT_OPTIONS, context.options[0] || {})`  to prevent that.

File: tests/lib/rules/module-files-only.test.js [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+   '',
+   'someDefault();',
+   'export default someDefault();'
+);
+
+validImportAndExport = formatCode(
+   'import someDefault from \'someModule\';',
+   '',
+   'someDefault();',
+   'export = someDefault();'
```
Comment (yokuze) [inline tests/lib/rules/module-files-only.test.js:32]: Since we added a test for `export = `, should we also add a test for `import = require(...`: https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require ?

File: lib/rules/module-files-only.js [hunk 3]
```diff
@@ -0,0 +1,31 @@
+/**
+ * @fileoverview Ensures that all files are modules (either import or export)
```
Comment (yokuze) [inline lib/rules/module-files-only.js:2]: Is this really a TypeScript only rule? If so, should we maybe make note of that here, perhaps with a link to the TypeScript documentation about `modules` and how not using `import` / `export` in a file pollutes the global namespace?

Comment (yokuze) [reply lib/rules/module-files-only.js:2]: Additionally, should we consider putting TypeScript-only rules in their own folder so that they are easier to identify?

**Review by yokuze — CHANGES_REQUESTED** [review]

File: lib/rules/module-files-only.js (hunk 3 above)
Comment (jimjenkins5) [reply lib/rules/module-files-only.js:2]: I don't think this is really TypeScript only rules.

I'm using the the TypeScript parser because we're testing against `export =` and `import = require`. This rule could also be used in ES6+ javascript files to prevent ambiguity in the processor. [Note the rule I based it on](https://github.com/benmosher/eslint-plugin-import/blob/HEAD/docs/rules/unambiguous.md)

With that in mind, there is only one other rule that might be considered "TypeScript only", 1no-arrow-for-class-property`. And really that one may be usable in ES6+ in the future. So I don't think putting them in a separate folder makes much sense.

**Comment by yokuze** [comment]
Looks good.

**Review by yokuze — APPROVED** [review]

**Review by jthomerson — APPROVED** [review]
Approved based on @yokuze's review.
